import ReadOnlyChartTableBody from '@/components/common/read-only-icu-chart/read-only-chart-table-body'
import ReadOnlyChartTableHeader from '@/components/common/read-only-icu-chart/read-only-chart-table-header'
import { Table } from '@/components/ui/table'
import type { IcuOrderColors } from '@/types/adimin'
import type { SelectedIcuOrder } from '@/types/icu/chart'

export default function DisplayExampleTable({
  localColorState,
}: {
  localColorState: IcuOrderColors
}) {
  return (
    <div className="relative">
      <Table className="border">
        <ReadOnlyChartTableHeader
          orderWidth={400}
          setOrderWidth={() => {}}
          orderCount={0}
        />

        <ReadOnlyChartTableBody
          orders={DUMMY_ORDERS}
          orderWidth={400}
          species={''}
          localColorState={localColorState}
        />
      </Table>

      <div className="absolute inset-0 flex h-full cursor-not-allowed items-center justify-center">
        <div className="rounded-sm bg-black/30 px-10 py-5 text-center text-white">
          <span className="text-xl font-bold">적용 예시</span>
        </div>
      </div>
    </div>
  )
}

const DUMMY_ORDERS: SelectedIcuOrder[] = [
  {
    id: 0,
    icu_chart_order_type: 'checklist',
    is_bordered: false,
    icu_chart_order_comment: null,
    icu_chart_order_id: '0',
    icu_chart_order_name: '체크리스트',
    icu_chart_order_time: [
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
    ],
    treatments: [],
  },
  {
    id: 1,
    icu_chart_order_type: 'fluid',
    is_bordered: false,
    icu_chart_order_comment: null,
    icu_chart_order_id: '1',
    icu_chart_order_name: '수액',
    icu_chart_order_time: [
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
    ],
    treatments: [],
  },
  {
    id: 2,
    icu_chart_order_type: 'injection',
    is_bordered: false,
    icu_chart_order_comment: null,
    icu_chart_order_id: '2',
    icu_chart_order_name: '주사',
    icu_chart_order_time: [
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
    ],
    treatments: [],
  },
  {
    id: 3,
    icu_chart_order_type: 'po',
    is_bordered: false,
    icu_chart_order_comment: null,
    icu_chart_order_id: '3',
    icu_chart_order_name: '경구',
    icu_chart_order_time: [
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
    ],
    treatments: [],
  },

  {
    id: 4,
    icu_chart_order_type: 'test',
    is_bordered: false,
    icu_chart_order_comment: null,
    icu_chart_order_id: '4',
    icu_chart_order_name: '검사',
    icu_chart_order_time: [
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
    ],
    treatments: [],
  },

  {
    id: 5,
    icu_chart_order_type: 'feed',
    is_bordered: false,
    icu_chart_order_comment: null,
    icu_chart_order_id: '6',
    icu_chart_order_name: '식이',
    icu_chart_order_time: [
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
    ],
    treatments: [],
  },
  {
    id: 6,
    icu_chart_order_type: 'manual',
    is_bordered: false,
    icu_chart_order_comment: null,
    icu_chart_order_id: '5',
    icu_chart_order_name: '기타',
    icu_chart_order_time: [
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
    ],
    treatments: [],
  },
] as const
